### ISSUE TITLE
Player sprite jittering on movement in the marton_movment_scripting branch

### ISSUE THREAD

**Issue by mnaray** [mnaray/Mystic_Island-Cortex#2]
**Describe the bug**
There is some jittering on the player sprite when moving around the map. It is probably caused by the cinemachine virtual camera not working properly.

**To Reproduce**
Literally move around the map as you usually would. (The cinemachine virtual camera has to be activated with the pixel perfect camera extension)

**Expected behavior**
The player sprite should not be jittering when moving. Instead, it is supposed to look crisp and clean.

**Screenshots**
I might attach some screenshots later if some of us don't understand what I mean.

**Additional context**
The cinemachine virtual camera has the pixel perfect camera extension bound to it. That extension is supposed to prevent this from happening.  
It does its job partially, but the player sprite still jitters from time to time.

**Comment by sanqro** [comment]
# Fix

We fixed the issue by building the project and running it outside of the Unity Editor.
